Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (1,'KS','Kansas','State','USA','USA');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (20,'AL','Alabama','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (2,'AK','Alaska','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (3,'AS','AMERICAN SAMOA','Protectorate','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (4,'AZ','Arizona','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (5,'AR','Arkansas','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (6,'CA','California','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (7,'CO','Colorado','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (8,'CT','Connecticut','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (9,'DE','Delaware','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (10,'DC','District of Columbia','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (11,'FM','Federated States of Micronesia','Protectorate','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (12,'FL','Florida','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (13,'GA','Georgia','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (14,'GU','Guam','Protectorate','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (15,'HI','Hawaii','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (16,'ID','Idaho','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (17,'IL','Illinois','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (18,'IN','Indiana','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (19,'IA','Iowa','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (21,'KY','Kentucky','State','USA','United States');
Insert into DISTRICT (DISTRICT_ID,DISTRICT_ABRV,DISTRICT_NAME,DISTRICT_LABEL,COUNTRY_CODE,COUNTRY_NAME) values (22,'LA','Louisiana','State','USA','United States');


INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Khilan', 25, 'Delhi', 1500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Komal', 22, 'MP', 4500.00 );
